from __future__ import annotations

import itertools
import json
import subprocess
import threading
from collections.abc import Callable, Mapping
from pathlib import Path
from queue import Empty, Queue
from typing import TextIO, TypedDict, cast

from loguru import logger
from pyln.client import Plugin
from pyln.client.plugin import Request

from jmpeerswap.proxy import DEFERRED_RESPONSE, DeferredResponse, UnixRPCProxy
from jmpeerswap.rendezvous import PeerSwapRendezvous

__all__ = ["DEFERRED_RESPONSE", "DeferredResponse", "PeerSwapRendezvous"]

PEERSWAP_INIT_TIMEOUT = 120.0
PEERSWAP_MANIFEST_TIMEOUT = 30.0


class _InitParams(TypedDict):
    options: dict[str, object]
    configuration: dict[str, object]


class _InitMessage(TypedDict):
    params: _InitParams


# This module is the standalone PeerSwap/CLN bridge. It deliberately does
# not load JoinMarket configuration, wallet state or transaction operations.
# PeerSwap's own manifest is exposed through this proxy so CLN sees the same
# RPC surface it would see from an unmodified PeerSwap plugin.


class PeerSwapProcess:
    """Run PeerSwap as a child JSON-RPC plugin."""

    def __init__(self, executable: str) -> None:
        self.executable = executable
        self.process: subprocess.Popen[str] | None = None
        self.manifest: dict[str, object] | None = None
        # Keep bridge-generated request IDs in a separate namespace from
        # IDs generated by the child plugin.
        self._next_id = itertools.count(-1, -1)
        self._pending: dict[int, Queue[dict[str, object]]] = {}
        self._pending_lock = threading.Lock()
        self._write_lock = threading.Lock()
        self._reader: threading.Thread | None = None
        self._initialiser: threading.Thread | None = None
        self._initialised = threading.Event()
        self._initialise_error: BaseException | None = None
        self._process_error: BaseException | None = None
        self._stopping = threading.Event()
        self._parent_rpc: Callable[[str, object], object] | None = None
        self._parent_notification: Callable[[str, object], None] | None = None

    def start(self, manifest_params: dict[str, object] | None = None) -> None:
        if self.process is not None:
            raise RuntimeError("PeerSwap is already running")

        process = subprocess.Popen(
            [self.executable],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            text=True,
            bufsize=1,
        )
        self.process = process
        self._stopping.clear()
        self._initialised.clear()
        self._initialise_error = None
        self._process_error = None
        self._reader = threading.Thread(
            target=self._reader_loop,
            name="jm-peerswap-rpc",
            daemon=True,
        )
        self._reader.start()

        try:
            result = self._request(
                1,
                "getmanifest",
                manifest_params or {},
                timeout=PEERSWAP_MANIFEST_TIMEOUT,
            )
            if not isinstance(result, dict):
                raise RuntimeError("PeerSwap returned an invalid getmanifest result")
        except BaseException:
            self.stop()
            raise
        self.manifest = result

    def initialise(
        self,
        options: dict[str, object],
        configuration: dict[str, object],
    ) -> object:
        return self._request(
            next(self._next_id),
            "init",
            {"options": options, "configuration": configuration},
            timeout=PEERSWAP_INIT_TIMEOUT,
        )

    def stop(self) -> None:
        process = self.process
        self.process = None
        self._stopping.set()
        if process is None:
            return

        if process.stdin is not None:
            try:
                process.stdin.close()
            except (BrokenPipeError, OSError):
                pass

        try:
            process.terminate()
        except ProcessLookupError:
            pass
        else:
            try:
                process.wait(timeout=5)
            except subprocess.TimeoutExpired:
                try:
                    process.kill()
                except ProcessLookupError:
                    pass
                process.wait(timeout=5)

        reader = self._reader
        self._reader = None
        if reader is not None and reader is not threading.current_thread():
            reader.join(timeout=1)

        initialiser = self._initialiser
        self._initialiser = None
        if initialiser is not None and initialiser is not threading.current_thread():
            initialiser.join(timeout=1)

        self._fail_pending("PeerSwap stopped")

    def set_parent_rpc(self, callback: Callable[[str, object], object]) -> None:
        self._parent_rpc = callback

    def set_parent_notification(self, callback: Callable[[str, object], None]) -> None:
        self._parent_notification = callback

    def initialise_async(
        self,
        options: dict[str, object],
        configuration: dict[str, object],
    ) -> None:
        if self._initialiser is not None and self._initialiser.is_alive():
            raise RuntimeError("PeerSwap initialisation is already running")

        self._initialised.clear()
        self._initialise_error = None

        def initialise() -> None:
            try:
                self.initialise(options, configuration)
            except BaseException as exc:
                self._initialise_error = exc
                self.stop()
            finally:
                self._initialised.set()

        self._initialiser = threading.Thread(
            target=initialise,
            name="jm-peerswap-init",
            daemon=True,
        )
        self._initialiser.start()

    def wait_initialised(self) -> None:
        if not self._initialised.wait(timeout=PEERSWAP_INIT_TIMEOUT):
            self.stop()
            raise TimeoutError(
                f"PeerSwap initialisation timed out after {PEERSWAP_INIT_TIMEOUT:.0f}s"
            )
        error = self._initialise_error
        if error is not None:
            raise RuntimeError("PeerSwap initialisation failed") from error
        process_error = self._process_error
        if process_error is not None:
            raise RuntimeError("PeerSwap child process failed") from process_error

    def request(self, method: str, params: object) -> object:
        self.wait_initialised()
        request_id = next(self._next_id)
        logger.info("jm-peerswap child RPC -> {} id={}", method, request_id)
        try:
            result = self._request(request_id, method, params)
        except Exception as exc:
            logger.exception(
                "jm-peerswap child RPC <- {} id={} error={}",
                method,
                request_id,
                exc,
            )
            raise
        logger.info("jm-peerswap child RPC <- {} id={} ok", method, request_id)
        return result

    def notify(self, method: str, params: object) -> None:
        self.wait_initialised()
        self._write({"jsonrpc": "2.0", "method": method, "params": params})

    def _request(
        self,
        request_id: int,
        method: str,
        params: object,
        *,
        timeout: float | None = None,
    ) -> object:
        process = self.process
        if process is None or process.stdin is None:
            raise RuntimeError("PeerSwap is not running")
        process_error = self._process_error
        if process_error is not None:
            raise RuntimeError("PeerSwap child process failed") from process_error

        response_queue: Queue[dict[str, object]] = Queue(maxsize=1)
        with self._pending_lock:
            self._pending[request_id] = response_queue

        try:
            self._write(
                {
                    "jsonrpc": "2.0",
                    "id": request_id,
                    "method": method,
                    "params": params,
                }
            )
            try:
                response = response_queue.get(timeout=timeout)
            except Empty as exc:
                raise TimeoutError(
                    f"PeerSwap RPC {method} timed out after {timeout:.0f}s"
                ) from exc
        finally:
            with self._pending_lock:
                self._pending.pop(request_id, None)

        if "error" in response:
            raise RuntimeError(str(response["error"]))
        return response.get("result")

    def _write(self, message: dict[str, object]) -> None:
        process = self.process
        if process is None or process.stdin is None:
            raise RuntimeError("PeerSwap is not running")

        with self._write_lock:
            process.stdin.write(json.dumps(message) + "\n\n")
            process.stdin.flush()

    def _reader_loop(self) -> None:
        process = self.process
        if process is None or process.stdout is None:
            return

        stream = cast(TextIO, process.stdout)
        try:
            while not self._stopping.is_set():
                line = stream.readline()
                if not line:
                    break
                if not line.strip():
                    continue

                try:
                    message = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if not isinstance(message, dict):
                    continue

                request_id = message.get("id")
                if isinstance(request_id, int) and not isinstance(request_id, bool):
                    with self._pending_lock:
                        response_queue = self._pending.get(request_id)
                    if response_queue is not None:
                        response_queue.put(message)
                        continue

                method = message.get("method")
                if not isinstance(method, str):
                    continue

                params = message.get("params", {})
                if request_id is not None:
                    self._handle_child_request(request_id, method, params)
                elif self._parent_notification is not None:
                    self._parent_notification(method, params)
        finally:
            if not self._stopping.is_set():
                self._process_error = RuntimeError("PeerSwap exited unexpectedly")
                self._fail_pending("PeerSwap exited before responding")

    def _handle_child_request(
        self, request_id: object, method: str, params: object
    ) -> None:
        callback = self._parent_rpc
        if callback is None:
            self._send_error(request_id, -32603, "Parent RPC is not available")
            return

        logger.info("jm-peerswap child -> parent RPC {} id={}", method, request_id)
        try:
            result = callback(method, params)
        except Exception as exc:
            logger.exception(
                "jm-peerswap child -> parent RPC {} id={} error={}",
                method,
                request_id,
                exc,
            )
            self._send_error(request_id, -32603, str(exc))
            return

        logger.info("jm-peerswap child <- parent RPC {} id={} ok", method, request_id)
        self._write({"jsonrpc": "2.0", "id": request_id, "result": result})

    def _send_error(self, request_id: object, code: int, message: str) -> None:
        self._write(
            {
                "jsonrpc": "2.0",
                "id": request_id,
                "error": {"code": code, "message": message},
            }
        )

    def _fail_pending(self, message: str) -> None:
        with self._pending_lock:
            pending = list(self._pending.values())
        for response_queue in pending:
            response_queue.put({"error": {"message": message}})


def _forward_method(
    request: Request,
    process: PeerSwapProcess | None,
    method: str,
) -> object:
    if process is None:
        raise RuntimeError("PeerSwap is not running")
    return process.request(method, request.params)


def _forward_custommsg(
    request: Request,
    process: PeerSwapProcess | None,
    plugin: Plugin,
) -> dict[str, str]:
    """Forward ``custommsg`` without holding CLN's hook open.

    PeerSwap handles incoming custom messages synchronously. In particular, a
    swap-out agreement can cause PeerSwap to call ``pay`` while processing the
    custom message. Waiting for the child hook response here would keep CLN's
    ``custommsg`` hook active while that payment is waiting for CLN to finish
    delivering the original message. That creates a hook-level deadlock until
    CLN's 30-second hook timeout fires.

    PeerSwap's custom message hook always returns ``continue`` so the bridge
    can acknowledge the CLN hook immediately and let the child finish the
    message handling asynchronously.
    """
    if process is None:
        raise RuntimeError("PeerSwap is not running")

    def forward() -> None:
        try:
            process.request("custommsg", request.params)
        except Exception:
            logger.exception("jm-peerswap custommsg dispatch failed")

    threading.Thread(
        target=forward,
        name="jm-peerswap-custommsg",
        daemon=True,
    ).start()
    return {"result": "continue"}


def _handle_proxy_request(
    request: dict[str, object],
    respond: Callable[[dict[str, object]], None],
    rendezvous: PeerSwapRendezvous,
) -> dict[str, object] | DeferredResponse | None:
    method = request.get("method")
    if method not in {"txprepare", "txsend", "txdiscard"}:
        return None

    request_id = request.get("id")
    if request_id is None:
        return None

    params = request.get("params", {})
    if method == "txprepare" and isinstance(params, dict):
        outputs = params.get("outputs")
        output_count = len(outputs) if isinstance(outputs, list) else "?"
        logger.info(
            "jm-peerswap proxy intercepted txprepare id={} outputs={}",
            request_id,
            output_count,
        )
    else:
        logger.info(
            "jm-peerswap proxy intercepted {} id={}",
            method,
            request_id,
        )

    rendezvous_request_id = rendezvous.submit(method, params, request_id, respond)
    if rendezvous_request_id is not None:
        set_disconnect_handler = getattr(respond, "set_disconnect_handler", None)
        if callable(set_disconnect_handler):
            set_disconnect_handler(lambda: rendezvous.cancel(rendezvous_request_id))
    return DEFERRED_RESPONSE


def _make_forwarder(
    process: PeerSwapProcess, method: str, description: str | None
) -> Callable[..., object]:
    def forward(request: Request, **params: object) -> None:
        # PeerSwap RPCs such as peerswap-swap-out can remain in the child
        # process for tens of seconds while the protocol negotiates. Keep the
        # bridge's pyln dispatch loop free to service custommsg hooks and the
        # jmpeerswap rendezvous while that happens.
        def run() -> None:
            try:
                request.set_result(process.request(method, params))
            except Exception as exc:
                request.set_exception(exc)

        threading.Thread(
            target=run,
            name=f"jm-peerswap-forward-{method}",
            daemon=True,
        ).start()

    # pyln-client derives the advertised usage from the registered
    # callable's docstring when a description is supplied. The upstream
    # PeerSwap manifest provides a description separately, so preserve it
    # on the forwarding callable rather than leaving inspect.getdoc() to
    # return None.
    forward.__doc__ = description
    return forward


def _register_peer_swap_manifest(
    plugin: Plugin,
    process: PeerSwapProcess,
    manifest: dict[str, object],
) -> None:
    """Expose PeerSwap's manifest through the bridge plugin.

    The bridge is the process CLN talks to, but PeerSwap remains the owner of
    its RPC API. Registering the child's manifest here makes CLN dispatch
    PeerSwap's own method names to the child without introducing a second
    namespace or requiring a direct CLN connection from PeerSwap.
    """
    rpcmethods = manifest.get("rpcmethods", [])
    if not isinstance(rpcmethods, list):
        raise ValueError("PeerSwap manifest rpcmethods must be a list")

    for entry in rpcmethods:
        if not isinstance(entry, dict):
            raise ValueError("PeerSwap manifest rpcmethod must be an object")
        name = entry.get("name")
        if not isinstance(name, str) or not name:
            raise ValueError("PeerSwap manifest rpcmethod requires a name")
        if name in plugin.methods:
            raise ValueError(f"PeerSwap RPC method collides with bridge method: {name}")
        description = entry.get("description")
        if description is not None and not isinstance(description, str):
            raise ValueError(f"PeerSwap RPC method description is invalid: {name}")
        plugin.add_method(
            name,
            _make_forwarder(process, name, description),
            background=True,
            description=description,
        )

    options = manifest.get("options", [])
    if not isinstance(options, list):
        raise ValueError("PeerSwap manifest options must be a list")
    for entry in options:
        if not isinstance(entry, dict):
            raise ValueError("PeerSwap manifest option must be an object")
        name = entry.get("name")
        if not isinstance(name, str) or not name:
            raise ValueError("PeerSwap manifest option requires a name")
        if name in plugin.options:
            continue
        plugin.add_option(
            name,
            entry.get("default"),
            entry.get("description"),
            opt_type=entry.get("type", "string"),
            deprecated=entry.get("deprecated", False),
            multi=entry.get("multi", False),
            dynamic=entry.get("dynamic", False),
        )

    subscriptions = manifest.get("subscriptions", [])
    if not isinstance(subscriptions, list):
        raise ValueError("PeerSwap manifest subscriptions must be a list")
    for topic in subscriptions:
        if not isinstance(topic, str) or not topic:
            raise ValueError("PeerSwap manifest subscription must be a name")
        # ``shutdown`` belongs to the bridge plugin itself.  Registering the
        # child's subscription would attempt to install a second shutdown
        # handler and CLN rejects the manifest.
        if topic == "shutdown":
            continue
        plugin.add_subscription(
            topic,
            lambda plugin, topic=topic, **kwargs: process.notify(topic, kwargs),
        )

    notifications = manifest.get("notifications", [])
    if not isinstance(notifications, list):
        raise ValueError("PeerSwap manifest notifications must be a list")
    for entry in notifications:
        if not isinstance(entry, dict):
            raise ValueError("PeerSwap manifest notification must be an object")
        topic = entry.get("method")
        if not isinstance(topic, str) or not topic:
            raise ValueError("PeerSwap manifest notification requires a method")
        plugin.add_notification_topic(topic)

    hooks = manifest.get("hooks", [])
    if not isinstance(hooks, list):
        raise ValueError("PeerSwap manifest hooks must be a list")
    for entry in hooks:
        if isinstance(entry, str):
            name = entry
            before = after = filters = None
        elif isinstance(entry, dict):
            name = entry.get("name")
            before = entry.get("before")
            after = entry.get("after")
            filters = entry.get("filters")
        else:
            raise ValueError("PeerSwap manifest hook must be a name or object")

        if not isinstance(name, str) or not name:
            raise ValueError("PeerSwap manifest hook requires a name")
        if name == "custommsg":

            def callback(
                request: Request, method: str = name, **kwargs: object
            ) -> object:
                return _forward_custommsg(request, process, plugin)
        else:

            def callback(
                request: Request, method: str = name, **kwargs: object
            ) -> object:
                return _forward_method(request, process, method)

        plugin.add_hook(
            name,
            callback,
            before=before,
            after=after,
            filters=filters,
        )

    featurebits = manifest.get("featurebits")
    if isinstance(featurebits, dict):
        for key in ("init", "node", "invoice"):
            value = featurebits.get(key)
            if value is not None:
                plugin.featurebits[key] = value

    if "custommessages" in manifest:
        custommessages = manifest["custommessages"]
        if not isinstance(custommessages, list):
            raise ValueError("PeerSwap manifest custommessages must be a list")
        plugin.custom_msgs = custommessages

    dynamic = manifest.get("dynamic")
    if isinstance(dynamic, bool):
        plugin.dynamic = dynamic


def _register_rendezvous_methods(
    plugin: Plugin,
    rendezvous: PeerSwapRendezvous,
) -> None:
    """Register the CLN-only rendezvous endpoints.

    ``jmpeerswap-request`` deliberately runs in the background: the CLN
    request remains outstanding until a PeerSwap request is matched, after
    which ``Request.set_result`` sends the response to the original
    ``jm-lightning`` RPC client.
    """
    plugin.add_method(
        "jmpeerswap-request",
        rendezvous.wait,
        background=True,
    )
    plugin.add_method(
        "jmpeerswap-response",
        rendezvous.respond,
    )
    plugin.add_method(
        "jmpeerswap-cancel",
        rendezvous.wait_cancel,
        background=True,
    )


def _peer_swap_executable(
    plugin: Plugin, options: Mapping[str, object] | None = None
) -> str:
    configured = options
    if configured is None:
        plugin_options = getattr(plugin, "options", {})
        configured = plugin_options if isinstance(plugin_options, Mapping) else {}

    executable = configured.get("peerswap-plugin", "peerswap")
    if not isinstance(executable, str) or not executable:
        raise ValueError("peerswap-plugin must be a non-empty path")
    return executable


def _wire_parent_callbacks(plugin: Plugin, process: PeerSwapProcess) -> None:
    """Connect child plugin-protocol requests and notifications to CLN."""

    def parent_rpc(method: str, params: object) -> object:
        if plugin.rpc is None:
            raise RuntimeError("Core Lightning RPC is not ready")
        return plugin.rpc.call(method, params)

    def parent_notification(method: str, params: object) -> None:
        # PeerSwap uses the plugin protocol's ``log`` notification for its
        # startup and runtime logging. ``Plugin.notify`` sends a notification
        # in the opposite direction, so using it here silently discards the
        # child's log messages from lightningd's log.
        if method == "log":
            if not isinstance(params, Mapping):
                plugin.log(str(params))
                return

            message = params.get("message")
            if not isinstance(message, str):
                plugin.log(str(params))
                return

            level = params.get("level", "info")
            if not isinstance(level, str):
                level = "info"
            plugin.log(message, level=level)
            return

        plugin.notify(method, params)

    process.set_parent_rpc(parent_rpc)
    process.set_parent_notification(parent_notification)


def _rewrite_init(message: Mapping[str, object]) -> tuple[Path, Path]:
    params = message.get("params")
    if not isinstance(params, Mapping):
        raise ValueError("PeerSwap init message params must be an object")

    configuration = params.get("configuration")
    if not isinstance(configuration, dict):
        raise ValueError("PeerSwap init configuration must be an object")

    rpc_file = configuration.get("rpc-file")
    lightning_dir_value = configuration.get("lightning-dir")
    if not isinstance(rpc_file, str) or not isinstance(lightning_dir_value, str):
        raise ValueError(
            "PeerSwap init configuration requires string rpc-file and lightning-dir"
        )

    cln_rpc = Path(rpc_file)
    lightning_dir = Path(lightning_dir_value)
    peerswap_rpc = lightning_dir / "peerswap-rpc"

    # PeerSwap's glightning client passes rpc-file to filepath.Join with
    # lightning-dir. It therefore expects rpc-file to be relative to the
    # Lightning data directory. Keep the bridge's absolute socket path
    # separate from the value handed to the child plugin.
    configuration["rpc-file"] = peerswap_rpc.name

    return cln_rpc, peerswap_rpc


def main() -> None:
    plugin = Plugin()
    plugin.add_option(
        "peerswap-plugin",
        "peerswap",
        "Path to the unmodified PeerSwap plugin executable.",
    )

    process: PeerSwapProcess | None = None
    proxy: UnixRPCProxy | None = None
    rendezvous = PeerSwapRendezvous()

    _register_rendezvous_methods(plugin, rendezvous)

    original_getmanifest = plugin.methods["getmanifest"].func

    def getmanifest(**params: object) -> object:
        nonlocal process
        if process is None:
            process = PeerSwapProcess("peerswap")
            process.start(params)
            if process.manifest is None:
                raise RuntimeError("PeerSwap did not return a manifest")
            _register_peer_swap_manifest(plugin, process, process.manifest)
        return cast(object, original_getmanifest(**params))

    plugin.methods["getmanifest"].func = getmanifest

    @plugin.init()  # type: ignore[untyped-decorator]
    def init(
        plugin: Plugin,
        options: dict[str, object],
        configuration: dict[str, object],
    ) -> None:
        nonlocal process, proxy

        executable = _peer_swap_executable(plugin, options)

        if process is None:
            process = PeerSwapProcess(executable)
            process.start()
        elif process.executable != executable:
            process.stop()
            process = PeerSwapProcess(executable)
            process.start()

        init_message: _InitMessage = {
            "params": {
                "options": {
                    key: value
                    for key, value in options.items()
                    if key != "peerswap-plugin"
                },
                "configuration": configuration,
            },
        }

        cln_rpc, peerswap_rpc = _rewrite_init(init_message)
        # The plugin is deliberately a transparent PeerSwap/CLN proxy.
        # JoinMarket transaction handling stays in jm-lightning. The two
        # processes rendezvous only through CLN RPC methods.
        proxy = UnixRPCProxy(
            peerswap_rpc,
            cln_rpc,
            lambda request, respond: _handle_proxy_request(
                request, respond, rendezvous
            ),
        )
        proxy.start()

        _wire_parent_callbacks(plugin, process)

        plugin.log("Starting asynchronous PeerSwap initialisation")
        process.initialise_async(
            init_message["params"]["options"],
            init_message["params"]["configuration"],
        )

    @plugin.subscribe("shutdown")  # type: ignore[untyped-decorator]
    def shutdown(plugin: Plugin, **kwargs: object) -> None:
        del plugin, kwargs
        rendezvous.stop()
        if proxy is not None:
            proxy.stop()
        if process is not None:
            process.stop()

    plugin.run()
